spring:
  application:
    name: firefly-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  security:
    user:
      # 默认user
      name: user
      password: password

server:
  port: 8888
