spring:
  application:
    name: firefly-auth
  datasource:
    url: jdbc:mysql://localhost:3306/spring-cloud-firefly?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: zhang
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        #指定jpa的自动表生成策略，驼峰自动映射为下划线格式
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibername:
        format_sql: true

server:
  port: 5000
  servlet:
    context-path: /uaa
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace

eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/
  instance:
    prefer-ip-address: true  # 采用ip注册
    #定义实例ID格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
